# Generated by Django 5.1.7 on 2025-03-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], default='100', max_length=3)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default='1', max_length=1)),
                ('credit_units', models.PositiveIntegerField(default=2)),
                ('course_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General Studies'), ('REQUIRED', 'Required')], default='Compulsory', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturers', models.ManyToManyField(blank=True, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='is_prerequisite_for', to='courses.course')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department')),
            ],
            options={
                'ordering': ['level', 'code'],
                'unique_together': {('code', 'department')},
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('NOTE', 'Lecture Note'), ('SLIDE', 'Slide Presentation'), ('TEXT', 'Textbook'), ('VIDEO', 'Video Material'), ('OTHER', 'Other')], max_length=5)),
                ('file', models.FileField(upload_to='course_materials/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis', models.TextField(help_text='Brief course description')),
                ('objectives', models.TextField(help_text='Course learning objectives')),
                ('topics', models.JSONField(default=list, help_text='List of topics and subtopics in JSON format')),
                ('references', models.TextField(help_text='Recommended textbooks and references')),
                ('grading_system', models.JSONField(default=dict, help_text='Grading breakdown in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('MID', 'Midterm Exam'), ('FIN', 'Final Exam'), ('QUZ', 'Quiz'), ('ASG', 'Assignment')], max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='past_questions/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'exam_type'],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('LEC', 'Lecture'), ('TUT', 'Tutorial'), ('LAB', 'Laboratory'), ('ASG', 'Assignment'), ('PRJ', 'Project'), ('EXM', 'Exam')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='unit_attachments/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
